### ISSUE TITLE
remark

### ISSUE THREAD

**Issue by fahiid33** [Humaminho/tic-tac-toe#1]
this shit is useless, i cant't with this guy !!

**Comment by Humaminho** [comment]
it ain't even done cock sucker please stop commenting! thank you

**Comment by fahiid33** [comment]
still useless brew $### $### *_* *_*

**Comment by fahiid33** [comment]
still useless brew $#### $#### *_* *_*

**Comment by fahiid33** [comment]
still useless brew *_* *_*

**Comment by fahiid33** [comment]
what would a man do with this webpage fr !!!

**Comment by fahiid33** [comment]
the replay button does not work at all !

**Comment by Humaminho** [comment]
thanks my friend problem solved!
